accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('find_username/', views.find_username, name='find_username'),
    path('login/kakao/', views.kakao_login, name="kakao_login"),
    path('login/kakao/callback/', views.kakao_login_callback, name="kakao_login_callback"),
    path('settings/edit/', views.user_edit, name="user_edit"),
    path('settings/change_password/', views.change_password, name="change_password"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done'),
        template_name='accounts/password_reset/reset_password.html',
        email_template_name='accounts/password_reset/password_reset_form.html',
    ), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_done.html'), name='password_reset_complete'),
]

base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

board/urls.py
from django.urls import path, include
from . import views
app_name = 'board'

urlpatterns = [
    path('<int:board_id>/', views.category, name='category'),
    path('<int:board_id>/article/<int:article_id>/', views.article_detail, name='detail'),
    path('<int:board_id>/article/<int:article_id>/comment/write/', views.comment_write, name='comment_write'),
    path('<int:board_id>/article/<int:article_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:board_id>/write/', views.article_write, name='write'),
    path('<int:article_id>/modify/', views.article_modify, name='modify'),
    path('<int:article_id>/delete/', views.article_delete, name='delete'),
    path('article/like/', views.article_like, name='article_like')

]

base/views.py
from django.core.paginator import Paginator
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404
from board.models import Board, Article


def index(request: HttpRequest):

    article_list = Article.objects.filter(board=2).order_by('-id')[:10]

    context = {
        'article_list': article_list,

    }

    return render(request, "home/main.html", context)

base/templates/_form.html
{% load django_bootstrap5 %}

<div class="card">
    {% if form_title %}
    <div class="card-header">
        {{ form_title }}
    </div>
    {% endif %}
    <div class="card-body">
        {% if form %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-outline-primary">
                {{ submit_label|default:"Submit" }}
            </button>
        </form>
        {% else %}
        <div class="alert alert-danger">
            form 객체를 지정해주세요.
        </div>
        {% endif %}
    </div>
</div>

base/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

base/templates/layout.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>밍크</title>
    <!-- jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- swiper -->
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>

    <!-- bootstrap5 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>

    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- tailwind.css -->
    <link rel="stylesheet" href="{% static 'tailwind.output.css' %}">
    <!-- common.js -->
    <script defer src="{% static 'common.js' %}"></script>

    <link rel="shortcut icon" href="https://user-images.githubusercontent.com/85653591/162341727-cf25d79d-de4a-4c34-a83c-62545cd60cea.png">
</head>
<body class="t-flex t-flex-col t-min-h-screen t-pt-[56px] t-bg-slate-50">
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} t-my-[0px]">
    {{ message|safe }}
</div>
{% endfor %}
{% endif %}
<header>
    <nav class="navbar navbar-expand-lg fixed-top t-bg-orange-300">
        <div class="container">
            <!-- Site Logo Here -->
            <a class="navbar-brand" href="{%url 'index' %}"><i
                    class="t-text-orange-600 fas fa-paw"></i> <span class="t-text-white">밍크</span></a>
            <!-- Mobile Toggle Button -->
            <button class="navbar-toggler t-bg-orange-200" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarMobileToggle"
                    aria-controls="navbarMobileToggle" aria-expanded="false" aria-label="Toggle navigation"><i
                    class="fas fa-caret-down t-text-white"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarMobileToggle">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link t-w-fit text-decoration-none text-light" aria-current="page"
                           href="{% url 'board:category' 2%}">밍크마당</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link t-w-fit text-decoration-none text-light" aria-current="page"
                           href="{% url 'board:category' 1%}">공지사항</a>
                    </li>
                </ul>

                <!-- Right Side -->
                {% if user.is_authenticated %}
                <div class="btn-group float-end">
                    <div class="t-mr-5">
                        <a class="text-decoration-none text-light" href="{% url 'board:write' 2 %}">글 작성</a>
                    </div>
                    <a href="#"
                       class="dropdown-toggle text-decoration-none text-light" data-bs-toggle="dropdown">
                        <i class="bi bi-person-circle"></i>
                        <span> 프로필 </span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a href="{% url 'accounts:user_edit'%}" class="dropdown-item"><i
                                class="bi bi-gear-fill"></i> 사용자 정보</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="bi bi-gear-fill"></i>로그아웃</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </div>
                {% else %}
                <a href="{% url 'accounts:login'%}?next={{ request.path }}"
                   class="t-text-white hover:t-text-white t-w-fit nav-link">로그인</a>
                {% endif %}
            </div>
        </div>
    </nav>

</header>
{%block content%}
{%endblock%}
<footer class="t-bg-orange-200 t-flex t-mt-auto t-h-[50px]">
    <span class="t-m-auto"><i class="fas fa-paw"></i> 밍크</span>
</footer>
</body>
</html>