base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

board/urls.py
from django.urls import path, include
from . import views
app_name = 'board'

urlpatterns = [
    path('<int:board_id>/', views.category, name='category'),
    path('<int:board_id>/article/<int:article_id>/', views.article_detail, name='detail'),
    path('<int:board_id>/article/<int:article_id>/comment/write/', views.comment_write, name='comment_write'),
    path('<int:board_id>/article/<int:article_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:board_id>/write/', views.article_write, name='write'),
    path('<int:article_id>/modify/', views.article_modify, name='modify'),
    path('<int:article_id>/delete/', views.article_delete, name='delete'),
    path('article/like/', views.article_like, name='article_like')

]

board/models.py
import re

from django.db import models
from django_summernote.models import AbstractAttachment, Attachment
from django.conf import settings
from accounts.models import User
from datetime import datetime, timedelta, timezone


# Create your models here.
class Board(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    name = models.CharField('상품명(내부용)', max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('수정날짜', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_article')
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    subject = models.CharField('제목', max_length=100)
    content = models.TextField('내용')
    tag = models.CharField('태그', max_length=100)
    is_blind = models.BooleanField('공개 여부', default=False)
    voter = models.ManyToManyField(User, related_name='voter_article')
    writer = models.CharField('글쓴이', max_length=100)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.reg_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.reg_date.date()
            return str(time.days) + '일 전'
        else:
            return str(time.days) + '일 전'

    def count_voter_user(self):
        return self.voter.count()

    def __str__(self):
        return self.subject

    def extract_attachments(self) -> list[AbstractAttachment, ...]:
        img_urls = re.findall(r'src="(.*?)"', self.content)
        img_urls = [img_url.replace(settings.MEDIA_URL, '') for img_url in img_urls]


        return img_urls

    def img_thumbnail(self):
        img_root = "/media/"
        icon_hidden = 'https://user-images.githubusercontent.com/85653591/157589936-bef76f01-c4eb-4378-8c42-f109d4169b9a.png'

        img = self.extract_attachments()
        if len(img) >= 1:
            img_url = img[0]
        else:
            img_url = None

        if img_url is not None:
            if 'django-summernote' in img_url:
                return img_root + img_url
            return img_url
        else:
            return icon_hidden


class Comment(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('수정날짜', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    content = models.TextField('내용')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comment')
    is_modify = models.BooleanField('수정 가능 여부', default=False)
    voter = models.ManyToManyField(User, related_name='voter_comment')

    def __str__(self):
        return self.content

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.reg_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.reg_date.date()
            return str(time.days) + '일 전'
        else:
            return False

board/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from board.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article  # 사용할 모델
        fields = ['subject', 'content', 'tag']
        widgets = {
            'content': SummernoteWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['subject'].label = '제목'
        self.fields['subject'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control t-my-3',
            'autofocus': True,
        })
        self.fields['tag'].label = '태그'
        self.fields['tag'].widget.attrs.update({
            'placeholder': '태그를 입력해주세요.   ex) #동물 #유머',
            'class': 'form-control t-my-3',
            'autofocus': True,
        })


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # 사용할 모델
        fields = ['content']

board/views.py
# Create your views here.
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .forms import ArticleForm, CommentForm
from board.models import Board, Article, Comment
from datetime import datetime, timedelta, timezone



def category(request: HttpRequest, board_id):
    return article_list(request, board_id)


def article_list(request: HttpRequest, board_id):
    board = get_object_or_404(Board, id=board_id)

    kw = request.GET.get('kw', '')
    page = request.GET.get('page', '1')  # 페이지
    if not kw:
        article_list = Article.objects.filter(board=board.id).order_by('-id')

    else:
        article_list = Article.objects.filter(board=board.id, ).filter(
            Q(tag__icontains=kw) | Q(subject__icontains=kw) | Q(content__icontains=kw)).order_by('-id')

    paginator = Paginator(article_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    best_articles = Article.objects.filter(board=board.id).order_by('-id')[:10]

    context = {'article_list': page_obj,
               'board': board,
               'best_articles': best_articles,
               }
    return render(request, 'board/article_list.html', context)


def article_detail(request: HttpRequest, board_id, article_id):
    article = get_object_or_404(Article, id=article_id)
    board = get_object_or_404(Board, id=article.board_id)
    comment = Comment.objects.filter(article_id=article_id)

    kw = request.GET.get('kw', '')
    page = request.GET.get('page', '1')  # 페이지
    #img_urls = article.img_thumbnail()

    if not kw:
        article_list = Article.objects.filter(board=board.id).order_by('-id')

    else:
        article_list = Article.objects.filter(board=board.id, ).filter(
            Q(tag__icontains=kw) | Q(subject__icontains=kw) | Q(content__icontains=kw)).order_by('-id')

    paginator = Paginator(article_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'article': article,
               'board': board,
               'comment': comment,
               'article_list': page_obj,
            #   'img_url': img_urls,
               }
    return render(request, 'board/article_detail.html', context)

@login_required
def article_write(request: HttpRequest, board_id):
    if board_id == 1 and request.user.is_superuser != 1:
        return HttpResponse("잘못된 접근입니다.")

    if request.user.is_authenticated:
        board = Board.objects.get(id=board_id)
        returnUrl = f"/board/{board.id}"
        if request.method == 'POST':
            form = ArticleForm(request.POST)
            if form.is_valid():
                article = form.save(commit=False)
                article.board_id = board.id
                article.user_id = request.user.id
                article.writer = request.user.username
                article.save()
                return redirect(returnUrl)
        else:
            form = ArticleForm()
        context = {'form': form,
                   }
        return render(request, 'board/article_form.html', context)
    else:
        return redirect('accounts:login')


@login_required
def article_modify(request: HttpRequest, article_id):
    article = get_object_or_404(Article, id=article_id)
    board_id = article.board_id
    board = get_object_or_404(Board, id=board_id)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            messages.success(request, "질문이 수정되었습니다.")
            return redirect(f"/board/{board_id}")
    else:
        form = ArticleForm(None, instance=article)

    return render(request, "board/article_form.html", {
        "form": form,
        "board": board,
    })


@login_required
def article_delete(request: HttpRequest, article_id):
    article = get_object_or_404(Article, id=article_id)
    board_id = article.board_id
    article.delete()
    messages.success(request, "질문이 삭제되었습니다.")
    return redirect(f"/board/{board_id}")


@login_required
def comment_write(request: HttpRequest, board_id, article_id):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, id=article_id)
        returnUrl = f"/board/{article.board_id}/article/{article.id}/"
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.article_id = article.id
                comment.user_id = request.user.id
                comment.save()
                return redirect(returnUrl)
        else:
            return redirect(returnUrl)
    else:
        return redirect('accounts:login')


@login_required
def comment_delete(request: HttpRequest, board_id, article_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    board_id = comment.article.board_id
    comment.delete()
    messages.success(request, "댓글이 삭제되었습니다.")
    return redirect(f"/board/{board_id}/article/{article_id}/")


@login_required
@require_POST
def article_like(request):
    pk = request.POST.get('pk', None)
    article = get_object_or_404(Article, pk=pk)
    user = request.user

    if request.user == article.user:
        return request

    if article.voter.filter(id=user.id).exists():
        article.voter.remove(user)
    else:
        article.voter.add(user)

    context = {'likes_count': article.count_voter_user()}
    return HttpResponse(json.dumps(context), content_type="application/json")

board/templates/board/article_form.html
{% extends 'layout.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="t-bg-slate-100">
    <div class="container">
        <h1 class="t-pt-3 fs-1">게시글 등록</h1>
        <form method="post" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-outline-primary">저장하기</button>
            {% bootstrap_button button_type="reset" content="취소" button_class="btn-outline-primary" %}
        </form>
    </div>
</div>

<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $(".save").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });
</script>
{% endblock %}

board/templates/board/article_list.html
{% extends "layout.html" %}
{%block content%}

<section class="section-main-index sm:t-h-screen"
         style="background-image:url(https://user-images.githubusercontent.com/85653591/161883541-5978545f-9379-4f16-be32-628f02d4a296.jpg);">
    <div class="t-p-2 t-mx-auto t-container t-mt-[60px]">
        <div class="t-flex t-p-2">
            <!-- 글 미리보기 -->
            <div class="article-best-list t-basis-2/3 sm:t-block t-hidden t-mr-1">
                {%if board.id == 1 %}
                <div class="article-best-list t-basis-2/3 sm:t-block t-hidden t-mr-1 t-h-full">
                    <div class=" t-h-full t-border-2 t-border-slate-200 t-bg-slate-100 t-opacity-90 t-p-10 t-w-full ">
                        <p class="t-inline-block t-mt-[25%] t-text-6xl t-w-full t-text-center ">
                                <span class="">
                                    <i class="fa-solid fa-paw t-text-9xl"></i>
                                </span>공지사항입니다.
                        </p>
                    </div>
                </div>
                {%else%}
                <div class="t-flex-row t-flex t-h-full t-border-b-2 t-border-r-2 t-border-slate-300 t-flex-wrap">
                    {% for article in article_list %}
                    <div class="t-bg-white t-opacity-90 t-basis-1/5 t-border-l-2 t-border-slate-300 t-h-1/2 t-bg-center t-bg-no-repeat	t-overflow-hidden t-bg-contain"
                         style="background-image:url({{article.img_thumbnail}});">
                        <div class="t-w-full t-truncate t-bg-slate-500 t-p-2 t-text-white t-border-y-2 t-border-slate-300">
                            <a href="{% url 'board:detail' 2 article.id%}?page={{article_list.number}}&kw={{request.GET.kw}}"
                               class="hover:t-text-blue-300">
                                {{article.subject}}
                            </a>
                        </div>
                    </div>
                    {%endfor%}
                </div>
                {%endif%}
            </div>
            <!-- 글 미리보기 끝-->

            <!-- 최신글리스트 -->
            <div class="article-list-box t-border-2 t-border-slate-300 t-mx-auto t-w-full sm:t-basis-1/3 t-bg-slate-50 t-opacity-90 t-p-1">
                {% for article in article_list %}
                {% if forloop.first %}
                <div class="t-border-2 t-border-slate-200 t-p-1 t-m-1">
                    <a href="{% url 'index' %}" class="t-text-orange-300 t-text-2xl"><i class="fas fa-paw
hover:t-text-blue-300"></i>&nbsp; {{board.name}}</a>
                </div>
                {%endif%}
                <div class="t-border-2 t-border-slate-200 t-p-1 t-m-1 hover:t-bg-slate-300">
                    <div class="">
                        <a href="{% url 'board:detail' 2 article.id%}?page={{article_list.number}}&kw={{request.GET.kw}}"
                           class="">
                            {{article.subject }}
                        </a>
                        <span class="t-text-green-300">[{{article.comment.count}}]</span>
                    </div>
                    <div class="t-flex t-justify-between">
                        <div class="article-regdate-box t-pt-[2px]">
                            <p class="t-text-sm t-text-slate-400">
                                <i class="fa-regular fa-clock"></i>
                                {% if article.created_string == False %}
                                {{ article.created|date:'m월 d일' }}
                                {% else %}
                                {{ article.created_string }}
                                {% endif %}
                            </p>
                        </div>
                        <div class="writer-nickname-box">
                            <p><i class="fa-regular fa-user"></i> {{article.writer}}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.last %}
                <div class="t-p-2 t-text-center">
                    <a href="/board/2/"
                       class="t-font-bold t-text-2xl t-bg-slate-50 t-opacity-90 t-p-2 t-rounded-2xl t-border-2 t-border-slate-200">더
                        보기</a>
                </div>
                {%endif%}
                {%endfor%}
            </div>
            <!-- 최신글리스트 끝-->
        </div>
    </div>
</section>
{%endblock%}