accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('find_username/', views.find_username, name='find_username'),
    path('login/kakao/', views.kakao_login, name="kakao_login"),
    path('login/kakao/callback/', views.kakao_login_callback, name="kakao_login_callback"),
    path('settings/edit/', views.user_edit, name="user_edit"),
    path('settings/change_password/', views.change_password, name="change_password"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done'),
        template_name='accounts/password_reset/reset_password.html',
        email_template_name='accounts/password_reset/password_reset_form.html',
    ), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_done.html'), name='password_reset_complete'),
]

base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

accounts/models.py
from __future__ import annotations
from typing import TYPE_CHECKING

from django.contrib.sessions.backends import file

if TYPE_CHECKING:
    from accounts.forms import SignupForm

import os
import random
from io import BytesIO
from urllib.parse import urlparse
from urllib.request import urlopen
from django.contrib.auth import login
from django.contrib.auth.models import AbstractUser
from django.core.files import File
from django.db import models
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import resolve_url, redirect
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.template.loader import render_to_string


class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"

    class ProviderTypeCodeChoices(models.TextChoices):
        LOCAL = "local", "로컬"
        KAKAO = "kakao", "카카오"

    first_name = None
    last_name = None
    date_joined = None

    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    nickname = models.CharField('닉네임', max_length=100)
    name = models.CharField('이름', max_length=100)
    gender = models.CharField('성별', max_length=1, blank=True, choices=GenderChoices.choices)
    profile_img = models.ImageField('프로필이미지', blank=True, upload_to="accounts/profile_img/%Y/%m/%d",
                                    help_text="gif/png/jpg 이미지를 업로드해주세요.")

    provider_type_code = models.CharField('프로바이더 타입코드', max_length=20, choices=ProviderTypeCodeChoices.choices,
                                          default=ProviderTypeCodeChoices.LOCAL)
    provider_accounts_id = models.PositiveIntegerField('프로바이더 회원번호', default=0)

    @staticmethod
    def login_with_kakao(request: HttpRequest, provider_accounts_id: int, provider_accounts_nickname: str,
                         provider_accounts_thumbnail_image_url: str):
        provider_type_code = User.ProviderTypeCodeChoices.KAKAO
        qs: QuerySet = User.objects.filter(provider_type_code=provider_type_code,
                                           provider_accounts_id=provider_accounts_id)

        if not qs.exists():
            username = provider_type_code + "__" + str(provider_accounts_id)
            name = provider_accounts_nickname if provider_accounts_nickname else username
            email = ""
            password = str(random.randint(1000, 9999))
            nickname = name
            user: User = User.objects.create_user(username=username, email=email, password=password, name=name,
                                                  provider_type_code=provider_type_code,
                                                  provider_accounts_id=provider_accounts_id,
                                                  nickname=nickname)

            if provider_accounts_thumbnail_image_url:
                provider_accounts_thumbnail_image_url_parsed = urlparse(provider_accounts_thumbnail_image_url)
                provider_accounts_thumbnail_image_file_name = os.path.basename(
                    provider_accounts_thumbnail_image_url_parsed.path)

                response = urlopen(provider_accounts_thumbnail_image_url)
                io = BytesIO(response.read())
                user.profile_img.save(provider_accounts_thumbnail_image_file_name, File(io))
        else:
            user: User = qs.first()

        login(request, user)

    @property
    def profile_img_url(self):
        if self.profile_img:
            return self.profile_img.url;
        return resolve_url('pydenticon_image', data=self.username)

    @classmethod
    def join(cls, username, email, password, name, provider_type_code, provider_accounts_id) -> User:
        user = User.objects.create_user(username=username, email=email, password=password, name=name,
                                        provider_type_code=provider_type_code,
                                        provider_accounts_id=provider_accounts_id)

        cls.after_join(user)

        return user

    @classmethod
    def join_by_form(cls, form: SignupForm) -> User:
        user = form.save()

        cls.after_join(user)

        return user

    @staticmethod
    def after_join(user: User) -> None:
        user.send_welcome_email()

    # https://github.com/askcompany-kr/django-with-react-rev2/ 참조
    def send_welcome_email(self):
        if not self.email:
            return

        subject = render_to_string("accounts/welcome_email_subject.txt", {
            "user": self,
        }).strip()

        content = render_to_string("accounts/welcome_email_content.txt", {
            "user": self,
        })

        sender_email = settings.WELCOME_EMAIL_SENDER
        send_mail(subject, content, sender_email, [self.email], fail_silently=False)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from accounts.models import User


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['name'].required = True
        self.fields['username'].label = '아이디'
        self.fields['profile_img'].widget.attrs['accept'] = 'image/png, image/gif, image/jpeg, image/jpg'

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'name', 'gender', 'password1', 'password2',  'nickname', 'profile_img']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email

class FindUsernameForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['name'].required = True

    class Meta:
        model = User
        fields = ['name', 'email']

accounts/views.py
import os

import requests
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from lazy_string import LazyString
from django.contrib.auth import update_session_auth_hash

from accounts.forms import SignupForm, FindUsernameForm
from .decorators import logout_required
from .models import User


# Create your views here.


@logout_required
def login(request: HttpRequest):
    return LoginView.as_view(template_name="accounts/login.html")(request)


@logout_required
def signup(request: HttpRequest):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            signed_user = User.join_by_form(form)
            auth_login(request, signed_user)
            messages.success(request, "회원가입이 완료되었습니다. 환영합니다.")
            next_url = request.GET.get('next', '/')
            return redirect(next_url)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


class MyLoginView(SuccessMessageMixin, LoginView):
    template_name = "accounts/signin.html"
    next_page = "/"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.success_message = LazyString(
            lambda: f'{self.request.user.name}님 환영합니다.')

    def get_initial(self):
        initial = self.initial.copy()
        initial['username'] = self.request.GET.get('username', None)

        return initial


def find_username(request: HttpRequest):
    if request.method == 'POST':
        form = FindUsernameForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']

            qs: QuerySet = User.objects.filter(email=email, name=name)

            if not qs.exists():
                messages.warning(request, "일치하는 회원이 존재하지 않습니다.")
            else:
                user: User = qs.first()
                messages.success(request, f"해당회원의 아이디는 {user.username} 입니다.")
                return redirect(reverse("accounts:login") + '?username=' + user.username)
    else:
        form = FindUsernameForm()

    return render(request, 'accounts/find_username.html', {
        'form': form,
    })


@logout_required
def kakao_login(request: HttpRequest):
    REST_API_KEY = os.environ.get("KAKAO_APP__REST_API_KEY")
    REDIRECT_URI = os.environ.get("KAKAO_APP__LOGIN__REDIRECT_URI")

    next = request.GET.get('next', '')
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code&state={next}"
    )


class KakaoException:
    pass


@logout_required
def kakao_login_callback(request):
    # (1)
    code = request.GET.get("code")
    REST_API_KEY = os.environ.get("KAKAO_APP__REST_API_KEY")
    REDIRECT_URI = os.environ.get("KAKAO_APP__LOGIN__REDIRECT_URI")

    # (2)
    token_request = requests.get(
        f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&code={code}"
    )
    # (3)
    token_json = token_request.json()
    error = token_json.get("error", None)
    if error is not None:
        raise Exception("카카오 로그인 에러")

    access_token = token_json.get("access_token")

    profile_request = requests.get(
        "https://kapi.kakao.com/v2/user/me",
        headers={"Authorization": f"Bearer {access_token}"},
    )
    profile_json = profile_request.json()

    id = profile_json.get("id")
    profile: dict = profile_json.get("kakao_account").get("profile")

    nickname = profile.get("nickname", "")
    thumbnail_image_url = profile.get("thumbnail_image_url", "")

    User.login_with_kakao(request, id, nickname, thumbnail_image_url)

    messages.success(request, f"{nickname}님 환영합니다. 카카오톡 계정으로 로그인되었습니다")

    next = request.GET.get('state', '')

    return redirect("index" if not next else next)


@login_required
def user_edit(request):

    user_id = request.user.id
    user = User.objects.get(id=user_id)
    return render(request, 'accounts/user_edit.html', {
        'user': user
    })

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, '비밀번호가 변경되었습니다.')
            return redirect('index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

accounts/templates/accounts/change_password.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{%block content%}
<div class="container t-flex t-flex-row t-h-10">
    <a class="t-text-2xl t-mr-4 t-leading-10 t-font-thin" href="#">개인정보 관리</a>
    <a class="t-text-2xl t-mr-4 t-leading-10 t-font-thin" href="#">비밀번호 변경</a>
    <a class="t-text-2xl t-leading-10" href="#">회원 탈퇴</a>
</div>
</nav>
<div class="t-bg-slate-100 t-h-screen">
    <div class="container t-mt-5">
        <div class="row">
            <div class="col-sm-6 offset-sm-3 t-bg-white t-border-2">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/find_username.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="t-bg-slate-100 t-h-screen">
<div class="container">
    <div class="row"></div>
    <div class="col-md-4 offset-md-4">
        <div class="login-form t-bg-white mt-4 p-4">
            <form>
                <h4>아이디 찾기</h4>
                <hr class="t-my-3">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="t-w-full t-text-right">
                <button class="btn btn-outline-primary" type="submit">아이디 찾기</button>
                </div>
            </form>
            <div class=" t-w-full t-mt-4 t-text-center">
                    <a href="{% url 'accounts:login' %}"
                       class="t-text-cyan-600 t-w-fit t-border-r-2 t-px-1 ">로그인</a>
                    <a href="{% url 'accounts:reset_password' %}"
                       class="t-text-cyan-600 t-w-fit t-border-r-2 t-pr-1">비밀번호찾기</a>
                    <a href="{% url 'accounts:signup'%}"
                       class="t-text-cyan-600 t-w-fit t-pr-1">회원가입</a>
                </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "layout.html" %}
{% block content %}
<div class="t-bg-slate-100 t-h-screen">
    <div class="container">
        <div class="row"></div>
        <div class="login-form t-bg-white p-4 t-mt-4 t-h-fit t-m-auto" style="width:22rem;">
            <form method="post" action="{% url 'accounts:login' %}" class="row g-3">
                <h4 class="t-my-4">로그인</h4>
                <hr>
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="col-12">
                    <label for="username">아이디</label>
                    <input type="text" name="username" class="form-control" placeholder="Username" id="username"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class=" col-12">
                    <label for="password">비밀번호</label>
                    <input type="password" name="password" class="form-control" placeholder="Password" id="password"
                           value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <input type="hidden" name="next" value="{{ next }}">
                <div class="col-12">
                    <button type="submit" class="btn btn-outline-primary float-end">로그인</button>
                </div>
            </form>
            <div class=" t-w-full t-mt-4 t-text-center">
                    <span>
                        <a href="{% url 'accounts:find_username' %}"
                           class="t-text-cyan-600 t-w-fit">아이디</a>
                        <i class="fas fa-genderless" style="color:gray; font-size: 0.75rem;"></i>
                        <a href="{% url 'accounts:reset_password' %}"
                           class="t-text-cyan-600 t-w-fit t-border-r-2 t-pr-1">비밀번호찾기</a>
                    </span>

                <a href="{% url 'accounts:signup'%}"
                   class="t-text-cyan-600 t-w-fit t-pr-1">회원가입</a>
            </div>
            <div>
                <button class="t-bg-yellow-400 btn btn-outline t-mt-3 t-w-full"
                        onclick="location.href='{% url 'accounts:kakao_login' %}?next={{request.GET.next}}'">
                    <i class="fa-solid fa-comment"></i> 카카오 로그인 </a>
                </button>
            </div>

        </div>
    </div>
</div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "layout.html" %}
{%block content%}
<div class="t-bg-slate-100 t-h-screen">
    <div class="container t-mt-5">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="회원가입" submit_label="회원가입" %}
            </div>
        </div>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/user_edit.html
{% extends "layout.html" %}

{%block content%}
<div class="container t-flex t-flex-row t-h-10">
    <a class="t-text-2xl t-mr-4 t-leading-10 t-font-thin" href="#">개인정보 관리</a>
    <a class="t-text-2xl t-mr-4 t-leading-10 t-font-thin" href="{% url 'accounts:change_password'%}">비밀번호 변경</a>
    <a class="t-text-2xl t-leading-10" href="#">회원 탈퇴</a>
</div>
</nav>
<div class="t-bg-slate-100 t-h-screen">
    <div class="container t-mt-5">
        <div class="row">
            <div class="col-sm-6 offset-sm-3 t-bg-white t-border-2">
                <p class="t-text-2xl t-mt-4">개인정보 관리</p>
                <hr class="t-mb-4">
                {% if user.email%}
                <p class="t-my-2">이메일 : {{user.email}}</p>
                {%endif%}
                <p class="t-my-2">아이디 : {{user.username}}</p>
                <p class="t-my-2">닉네임 : {{user.nickname}}</p>
                <p class="t-my-2">이름 : {{user.name}}</p>
                {{user.profile_img}}
                프로필 이미지 <img class="t-w-[22px] t-h-[22px] t-rounded-full t-object-fit t-inline-block"
                             src="/{{user.profile_img}}">
            </div>
        </div>
    </div>
</div>
{%endblock%}